<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find xxx_description)/robot/visual/properties.xacro"/>
  
  <xacro:macro name="pole" params="name translation_x translation_y">
    <link name="${name}_pole">
      <collision>
        <geometry>
          <cylinder radius="${POLE_RADIUS}" length="${POLE_HEIGHT}"/>
        </geometry>
      </collision>      
    </link>
    <joint name="${name}_pole_joint" type="fixed">
      <origin xyz="${translation_x} ${translation_y} ${(BASE_HEIGHT+POLE_HEIGHT)/2}"/>
      <parent link="base_link"/>
      <child link="${name}_pole"/>
    </joint>  
  </xacro:macro>
  <xacro:macro name="pole_set" params="">
    <xacro:pole 
      name="left_front"
      translation_x="${POLE_SEPARATION_X/2}"
      translation_y="${POLE_SEPARATION_Y/2}"
    />
    <xacro:pole 
      name="right_front"
      translation_x="${POLE_SEPARATION_X/2}"
      translation_y="${-POLE_SEPARATION_Y/2}"
    />
    <xacro:pole 
      name="left_rear"
      translation_x="${-POLE_SEPARATION_X/2}"
      translation_y="${POLE_SEPARATION_Y/2}"
    />
    <xacro:pole 
      name="right_rear"
      translation_x="${-POLE_SEPARATION_X/2}"
      translation_y="${-POLE_SEPARATION_Y/2}"
    />
        
  </xacro:macro>
</robot>
