<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find xxx_description)/urdf/visual/properties.xacro"/>
  <xacro:include filename="$(find xxx_description)/urdf/dynamics/properties.xacro"/>
  <xacro:include filename="$(find xxx_description)/urdf/visual/castor.xacro"/>
  
  <!-- Castor-->
  <xacro:macro name="castor" params="name translation_x translation_y namespace">
    <link name="${namespace}/${name}_castor">
      <xacro:castor_visual namespace="${namespace}"/>
      <inertial>
        <origin xyz="${CASTOR_COM}"/>
        <mass value="${CASTOR_M}"/>
        <inertia 
          ixx="${CASTOR_Ixx}"
          ixy="${CASTOR_Ixy}"
          ixz="${CASTOR_Ixz}"
          iyy="${CASTOR_Iyy}"
          iyz="${CASTOR_Iyz}"
          izz="${CASTOR_Izz}" 
        />
      </inertial>
      <collision>
        <geometry>
          <cylinder radius="${CASTOR_RADIUS}" length="${CASTOR_THICKNESS}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
    </link>
    <xacro:castor_joint
      name="${name}"
      translation_x="${translation_x}"
      translation_y="${translation_y}"
      namespace="${namespace}"
    />
  </xacro:macro>

  <!-- Contents-->
  <xacro:macro name="castor_set" params="namespace">
    <xacro:castor 
      name="right_front"
      translation_x="${CASTOR_SEPARATION_X/2}"
      translation_y="${CASTOR_SEPARATION_Y/2}"
      namespace="${namespace}"
    />
    <xacro:castor 
      name="left_front"
      translation_x="${CASTOR_SEPARATION_X/2}"
      translation_y="${-CASTOR_SEPARATION_Y/2}"
      namespace="${namespace}"
    />
    <xacro:castor 
      name="right_rear"
      translation_x="${-CASTOR_SEPARATION_X/2}"
      translation_y="${CASTOR_SEPARATION_Y/2}"
      namespace="${namespace}"
    />
    <xacro:castor 
      name="left_rear"
      translation_x="${-CASTOR_SEPARATION_X/2}"
      translation_y="${-CASTOR_SEPARATION_Y/2}"
      namespace="${namespace}"
    />
  </xacro:macro>
  
</robot>
