<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find xxx_description)/robot/visual/properties.xacro"/>
  <!-- Contents-->
  <xacro:macro name="sensor_link" params="">
    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder radius="${LIDAR_RADIUS}" length="${LIDAR_THICKNESS}"/>
        </geometry>
      </visual>
    </link>
    <joint name="lidar_mount" type="fixed">
      <origin xyz="${LIDAR_OFFSET} 0.0 ${(BASE_HEIGHT+LIDAR_THICKNESS)/2}"/>
      <parent link="base_link"/>
      <child link="lidar_link"/>
    </joint>
  
    <link name="camera_link">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <box size="0.025 0.09 0.025"/>
          </geometry>
      </visual>
    </link>
    <link name="camera_optical"/>
    <joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${CAMERA_OFFSET} 0 ${CAMERA_HEIGHT}" /> 
    </joint>
    <joint name="camera_optical_mount" type="fixed">
        <parent link="camera_link" />
        <child link="camera_optical" />
        <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" /> 
    </joint>
    <link name="imu_link"/>
    <joint name="imu_mount" type="fixed">
      <parent link="base_link" />
      <child link="imu_link" />
      <origin xyz="0 0 0" rpy="0 0 0" /> 
    </joint>
  </xacro:macro>
</robot>
