# offset of the center of the collision geometry 
offset:
- "0.25 0.0 -0.5"
- "0.375 0.0 0.0"
- "0.625 0.25 0.0"
# size of the collision geometry 
size:
- "0.4 0.25 1.0"
- "0.65 0.25 0.25"
- "1.15 0.50 0.25"
