mass:
- "1.0"
- "1.0"
- "1.0"
center_of_mass:
- "0.0 0.0 0.0"
- "0.0 0.0 0.0"
- "0.0 0.0 0.0"
inertia:
# xx,xy,xz,yy,yz,zz
# Link_1
- - "1.0"
  - "0.0"
  - "0.0"
  - "1.0"
  - "0.0"
  - "1.0"
# Link_2
- - "1.0"
  - "0.0"
  - "0.0"
  - "1.0"
  - "0.0"
  - "1.0"
# Link_3
- - "1.0"
  - "0.0"
  - "0.0"
  - "1.0"
  - "0.0"
  - "1.0"

