# offset of the center of the geometry 
offset:
- "0.25 0.0 -0.5"
- "0.375 0.0 0.0"
- "0.625 0.25 0.0"
# size of the geometry 
size:
- "0.5 0.25 1.0"
- "0.75 0.25 0.25"
- "1.25 0.50 0.25"
# link color
color: 
- "1 1 1 1"
- "1 1 1 1"
- "1 1 1 1"
