<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="description_package" value="dummy_description"/>
    <xacro:include filename="$(find ${description_package})/robot/visual/manipulator.xacro"/>
    <xacro:macro name="robot_link" params="link_id">
        <link name="link_${link_id}">
            <xacro:link_box_visual link_id="${link_id}"/>
        <inertial>
            <origin xyz="${COM[link_id-1]}"/>
            <mass value="${MASS[link_id-1]}"/>
            <inertia 
                ixx="${INERTIA[link_id-1][0]}" 
                ixy="${INERTIA[link_id-1][1]}" 
                ixz="${INERTIA[link_id-1][2]}" 
                iyy="${INERTIA[link_id-1][3]}" 
                iyz="${INERTIA[link_id-1][4]}" 
                izz="${INERTIA[link_id-1][5]}"/>
        </inertial>
        <collision>
            <origin xyz="${COLLISION_OFFSET[link_id-1]}"/>
            <geometry>
                <box size="${COLLISION_SIZE[link_id-1]}"/>
            </geometry>
        </collision>
        </link>
    </xacro:macro>
    <xacro:macro name="manipulator" params="package">
        <link name="world"/>
        <link name="link_0">
            <xacro:link_visual_0 />
            <inertial>
                <mass value="1.0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>         
        </link>
        <xacro:robot_link link_id="1" />
        <xacro:robot_link link_id="2" />
        <xacro:robot_link link_id="3" />
        <link name="end_effector"/>
        
        <xacro:base_offset/>
        <xacro:robot_joint link_id="1"/>
        <xacro:robot_joint link_id="2"/>
        <xacro:robot_joint link_id="3"/>
        <xacro:end_effector_offset/>
    </xacro:macro>
</robot>